use retail_data_analysis

select top 2 * from Customer
select top 2 * from Transactions
select top 2 * from prod_cat_info

--------case study 1(retail data analysis)------------

-------DATA PREPARATION AND UNDERSTANDING-------------

--1.what is the total number of rows in each of the 3 tables in the database?

	select 'customer' as TAB_LE ,count(*) as TOTAL_ROWS from Customer
	union
	select 'product', count(*) from prod_cat_info
	union
	select 'transaction', count(*) from Transactions


--2.what is the total number of transactions that have a return?

	select count(distinct transaction_id) as RETURNED_TRANSACTIONS from Transactions
	where Qty<0


--3.As you would have noticed,the dates provided across datasets are not in correct format. As first steps, please convert the data Variables 
--into valid date formats before proceeding ahead.
 
	update Customer
	set dob=CONVERT(date,dob,103)
	alter table customer
	alter column dob date

	update TRANSACTIONS
	set TRAN_DATE=convert(date,TRAN_DATE,103)
	alter table transactions
	alter column tran_date date

--4.What is the time range of the transaction data available for analysis?show the output in number of days,months and years 
--simultaneously in different columns.

	select 
	DATEDIFF(DAY,min(tran_date),max(tran_date))as days_diff,
	DATEDIFF(month,min(tran_date),max(tran_date))as month_diff,
	DATEDIFF(year,min(tran_date),max(tran_date))as years_diff 
	from Transactions


--5.Which product category does the sub category DIY belong to?

	select prod_cat,prod_subcat from prod_cat_info
	where prod_subcat='DIY'

------------DATA ANALYSIS-----------------------

--1.which channel is most frequently used for transactions? 

	select top 1 STORE_TYPE ,COUNT( distinct transaction_id) as COUNT_BY_CHANNEL from Transactions
	group by Store_type
	order by  COUNT_BY_CHANNEL desc


--2.What is the count of male and female customers in the database? 

	select GENDER,COUNT(GENDER) AS [COUNT_OF_(M/F)] from Customer
	group by GENDER
	having GENDER IN ('F','M')
	order by  [COUNT_OF_(M/F)] DESC


--3.From which city do we have the maximum number of customers how many? 

	select TOP 1 CITY_CODE,count(CITY_CODE) AS MAX_CUSTOMER from Customer
	group by CITY_CODE
	ORDER BY count(CITY_CODE) DESC


--4.How many subcategories are there under the books category? 

	select 'books' as category,count(prod_subcat)as total_subcat from prod_cat_info
	where prod_cat='books'


--5.What is the maximum quantity of products ever ordered? 

	select max(qty)as MAX_QTY_OF_PROD from Transactions


--6.What is the net total revenue generated in categories electronics and books? 

	select 'electronics+books' as category ,sum(total_amt) as net_revenue from prod_cat_info A 
	join Transactions B on A.prod_cat_code=B.prod_cat_code
	where prod_cat IN ('ELECTRONICS','BOOKS')


--7.How many customers have greater than 10 transactions with us, excluding returns?

	select count(*) as [customer_trans_action > 10] from (
	select cust_id, count(cust_id) as count_of_transactions from Transactions
	where Qty>0
	group by cust_id
	having count(cust_id)>10) total_cust


--8.What is the combined revenue earned  from the electronics and clothing categories from flagship stores? 

	select 'electronics + clothing'as products, ceiling(sum(total_amt))rev_enue from prod_cat_info A 
	left join Transactions B on A.prod_cat_code=B.prod_cat_code and A.prod_sub_cat_code=B.prod_subcat_code
	where prod_cat in ('electronics','clothing') and Store_type='flagship store'


--9.What is the total revenue generated from "male" customers in "electronics" category? Output should display total revenue by prod sub- cat.

	select gender,prod_cat,round(sum(total_amt),2) as rev_enue from Customer A  join Transactions B on A.customer_Id=B.cust_Id  join prod_cat_info C 
	on C.prod_cat_code=B.prod_cat_code
	where gender='m' and prod_cat='electronics'
	group by gender,prod_cat


--10.What is percentage of sales and returns by product subcategory display only top 5 subcategories in terms of sales?


	Select Top 5 prod_subcat,Sum(case WHEN total_amt > 0 THEN 1 ELSE 0 END) As 'Sales',
	Sum(case WHEN total_amt> 0 THEN 1.0 ELSE 0 END) /Count(*) *100 As '_percent',
	Sum(case WHEN total_amt < 0 THEN 1 ELSE 0 END) As 'Returns',
	Sum(case WHEN total_amt < 0 THEN 1.0 ELSE 0 END) /Count(*) *100 As 'Return_percent' From Transactions As T1
	INNER JOIN prod_cat_info As P1  ON T1.prod_subcat_code = P1.prod_sub_cat_code and T1.prod_cat_code = P1.prod_cat_code
	Group By prod_subcat 
	Order By sales desc

--11.For all customers aged between 25 to 35 years find what is the net total revenue generated by these customers
--in last 30 days of transactions from maximum transaction date available in the data?

	select DOB,DATEDIFF(year,DOB,GETDATE()) as [age_b/w_25-35],sum(total_amt) as total_revenue,DATEADD(day,-30,MAX(tran_date)) as last_tran_date from customer A 
	join Transactions B on A.customer_Id=B.cust_id 
	where DATEDIFF(year,DOB,GETDATE()) between 25 and 35
	group by DOB,tran_date,DATEDIFF(year,DOB,GETDATE())
	order by last_tran_date


--12.Which product category has seen the maximum value of returns in the last three months of transactions? 
 
	select top 1 * from (
		select prod_cat,sum(qty) as ret_urns,DATEADD(month,-3,MAX(tran_date)) as [last_3_month] from prod_cat_info A 
		join Transactions B on A.prod_cat_code=B.prod_cat_code
		group by prod_cat,Qty
		having sum(qty)<0)
	prod_cat_max
	order by ret_urns

--13.Which store type sells the maximum for rates by value of sales amount by quantity sold? 

	select store_type from (
	SELECT TOP 1 STORE_TYPE, sum(qty) AS SUM_QTY,SUM(TOTAL_AMT) AS TOT_SUM FROM TRANSACTIONS
	GROUP BY STORE_TYPE
	ORDER BY SUM_QTY DESC, TOT_SUM DESC)max_store_type


--14.What are the categories for which average revenue is above the overall average?

	select prod_cat,avg(total_amt)as [AVG_SALES > AVG_TOTAL_SALES],(select avg(total_amt) as avg_revenue from Transactions) AS AVG_TOTAL_SALES  from prod_cat_info A
	join Transactions B on A.prod_cat_code=B.prod_cat_code
	group by prod_cat
	having round(avg(total_amt),2)>(select avg(total_amt) as avg_revenue from Transactions)


--15.Find the average and total revenue by each sub category for the categories which are among top 5 categories in terms of quantity sold.

	select top 5 * from (
		select prod_cat,prod_subcat,sum(Qty) as sum_qty,AVG(total_amt) as avg_sales,total_amt as total_revenue from prod_cat_info A 
		left  join Transactions B on A.prod_cat_code=B.prod_cat_code and A.prod_sub_cat_code=B.prod_subcat_code
		group by prod_cat,prod_subcat,total_amt
		having SUM(qty)>0)a
	order by  sum_qty desc 
	









